# Data Manipulation #
<br><br><br>
Put stressors and colony sheets together because that data have common columns

In [1]:
#import needed libraries
import pandas as pd

#create dfs
stressors = pd.read_excel('stressors_clean.xlsx')
stressors

,State,Varroa Mites (Percent),Other pests and parasites (Percent),Diseases (percent),Pesticides (percent),Other (percent),Unknown (percent),Year
0,Alabama,10.0,5.4,0.0,2.2,9.1,9.4,2015-Q1
1,Arizona,26.9,20.5,0.1,0.0,1.8,3.1,2015-Q1
2,Arkansas,17.6,11.4,1.5,3.4,1.0,1.0,2015-Q1
3,California,24.7,7.2,3.0,7.5,6.5,2.8,2015-Q1
4,Colorado,14.6,0.9,1.8,0.6,2.6,5.9,2015-Q1
...,...,...,...,...,...,...,...,...
1099,Washington,15.5,2.4,1.0,0.0,5.3,0.0,2021-Q1
1100,West Virginia,13.7,3.4,0.7,2.6,1.2,3.3,2021-Q1
1101,Wisconsin,16.1,0.0,0.0,0.0,3.6,3.2,2021-Q1
1102,Wyoming,0.0,0.0,0.0,0.0,3.3,7.9,2021-Q1
1103,Other,19.4,1.2,4.1,0.0,6.8,1.1,2021-Q1

In [2]:
colony = pd.read_excel('colony_clean.xlsx')
colony

,State,Starting Colonies,Maximum Colonies,Lost Colonies,Percent Loss,Added Colonies,Renovated Colonies,Percent Renovated,Year
0,Alabama,7000,7000,1800,26,2800,250,4,2015-Q1
1,Arizona,35000,35000,4600,13,3400,2100,6,2015-Q1
2,Arkansas,13000,14000,1500,11,1200,90,1,2015-Q1
3,California,1440000,1690000,255000,15,250000,124000,7,2015-Q1
4,Colorado,3500,12500,1500,12,200,140,1,2015-Q1
...,...,...,...,...,...,...,...,...,...
1145,Washington,66000,122000,2900,2,9500,2600,2,2021-Q2
1146,West Virginia,8000,9000,170,2,1900,390,4,2021-Q2
1147,Wisconsin,42000,57000,2200,4,9000,7500,13,2021-Q2
1148,Wyoming,13500,30000,3400,11,7500,4900,16,2021-Q2
1149,Other,5970,8410,140,2,2890,3100,37,2021-Q2

In [3]:
# colony has 46 more rows
# do an outer merge and then search for NaN to find out what rows are missing in stressors
# merge on 'State' and 'Year'
outer_merge = pd.merge(colony, stressors, on = (['State', 'Year']), how = 'outer')
outer_merge.tail(50)

,State,Starting Colonies,Maximum Colonies,Lost Colonies,Percent Loss,Added Colonies,Renovated Colonies,Percent Renovated,Year,Varroa Mites (Percent),Other pests and parasites (Percent),Diseases (percent),Pesticides (percent),Other (percent),Unknown (percent)
1100,West Virginia,7000,7500,1200,16,1700,720,10,2021-Q1,13.7,3.4,0.7,2.6,1.2,3.3
1101,Wisconsin,25000,37000,2500,7,7000,170,0,2021-Q1,16.1,0.0,0.0,0.0,3.6,3.2
1102,Wyoming,13000,14500,1700,12,500,1200,8,2021-Q1,0.0,0.0,0.0,0.0,3.3,7.9
1103,Other,6640,6640,540,8,600,70,1,2021-Q1,19.4,1.2,4.1,0.0,6.8,1.1
1104,Alabama,9500,9500,2700,28,2800,930,10,2021-Q2,NaN,NaN,NaN,NaN,NaN,NaN
1105,Arizona,26000,26000,4200,16,8500,7500,29,2021-Q2,NaN,NaN,NaN,NaN,NaN,NaN
1106,Arkansas,12000,12000,1600,13,9000,6000,50,2021-Q2,NaN,NaN,NaN,NaN,NaN,NaN
1107,California,1050000,1060000,64000,6,200000,180000,17,2021-Q2,NaN,NaN,NaN,NaN,NaN,NaN
1108,Colorado,17000,22000,5500,25,4800,1100,5,2021-Q2,NaN,NaN,NaN,NaN,NaN,NaN
1109,Connecticut,3800,4000,60,2,960,400,10,2021-Q2,NaN,NaN,NaN,NaN,NaN,NaN
1110,Florida,300000,300000,33000,11,52000,31000,10,2021-Q2,NaN,NaN,NaN,NaN,NaN,NaN
1111,Georgia,135000,136000,20000,15,25000,18500,14,2021-Q2,NaN,NaN,NaN,NaN,NaN,NaN
1112,Hawaii,21000,21000,630,3,460,1200,6,2021-Q2,NaN,NaN,NaN,NaN,NaN,NaN
1113,Idaho,86000,120000,19500,16,40000,19000,16,2021-Q2,NaN,NaN,NaN,NaN,NaN,NaN
1114,Illinois,13000,13000,1100,8,3700,2100,16,2021-Q2,NaN,NaN,NaN,NaN,NaN,NaN
1115,Indiana,12000,12500,560,4,4000,1000,8,2021-Q2,NaN,NaN,NaN,NaN,NaN,NaN
1116,Iowa,26000,27000,2200,8,10500,3900,14,2021-Q2,NaN,NaN,NaN,NaN,NaN,NaN
1117,Kansas,7500,8000,870,11,4900,1600,20,2021-Q2,NaN,NaN,NaN,NaN,NaN,NaN
1118,Kentucky,10000,11500,270,2,2100,4500,39,2021-Q2,NaN,NaN,NaN,NaN,NaN,NaN
1119,Louisiana,29000,30000,2300,8,8000,2000,7,2021-Q2,NaN,NaN,NaN,NaN,NaN,NaN
1120,Maine,2000,18000,1100,6,430,260,1,2021-Q2,NaN,NaN,NaN,NaN,NaN,NaN
1121,Maryland,6500,7500,320,4,2600,690,9,2021-Q2,NaN,NaN,NaN,NaN,NaN,NaN
1122,Massachusetts,4000,10000,810,8,1400,310,3,2021-Q2,NaN,NaN,NaN,NaN,NaN,NaN
1123,Michigan,75000,97000,3500,4,10000,8000,8,2021-Q2,NaN,NaN,NaN,NaN,NaN,NaN
1124,Minnesota,69000,98000,5500,6,28000,4000,4,2021-Q2,NaN,NaN,NaN,NaN,NaN,NaN
1125,Mississippi,34000,35000,4800,14,9000,8000,23,2021-Q2,NaN,NaN,NaN,NaN,NaN,NaN
1126,Missouri,4800,4800,670,14,2000,670,14,2021-Q2,NaN,NaN,NaN,NaN,NaN,NaN
1127,Montana,38000,116000,3100,3,13500,15500,13,2021-Q2,NaN,NaN,NaN,NaN,NaN,NaN
1128,Nebraska,18500,37000,1800,5,8500,810,2,2021-Q2,NaN,NaN,NaN,NaN,NaN,NaN
1129,New Jersey,14500,19500,410,2,1400,140,1,2021-Q2,NaN,NaN,NaN,NaN,NaN,NaN
1130,New Mexico,5500,5500,540,10,80,2300,42,2021-Q2,NaN,NaN,NaN,NaN,NaN,NaN
1131,New York,29000,50000,3000,6,14500,4100,8,2021-Q2,NaN,NaN,NaN,NaN,NaN,NaN
1132,North Carolina,22000,23000,1700,7,6000,3300,14,2021-Q2,NaN,NaN,NaN,NaN,NaN,NaN
1133,North Dakota,42000,395000,4400,1,4800,3500,1,2021-Q2,NaN,NaN,NaN,NaN,NaN,NaN
1134,Ohio,13000,13500,820,6,6500,2400,18,2021-Q2,NaN,NaN,NaN,NaN,NaN,NaN
1135,Oklahoma,17000,17000,3600,21,4200,190,1,2021-Q2,NaN,NaN,NaN,NaN,NaN,NaN
1136,Oregon,80000,84000,3300,4,25000,19500,23,2021-Q2,NaN,NaN,NaN,NaN,NaN,NaN
1137,Pennsylvania,20000,23000,2100,9,7000,2800,12,2021-Q2,NaN,NaN,NaN,NaN,NaN,NaN
1138,South Carolina,18500,19500,1800,9,4100,5000,26,2021-Q2,NaN,NaN,NaN,NaN,NaN,NaN
1139,South Dakota,16500,198000,6500,3,39000,19000,10,2021-Q2,NaN,NaN,NaN,NaN,NaN,NaN
1140,Tennessee,12000,12000,720,6,4800,3400,28,2021-Q2,NaN,NaN,NaN,NaN,NaN,NaN
1141,Texas,385000,425000,34000,8,65000,72000,17,2021-Q2,NaN,NaN,NaN,NaN,NaN,NaN
1142,Utah,20000,31000,3500,11,8500,3900,13,2021-Q2,NaN,NaN,NaN,NaN,NaN,NaN
1143,Vermont,7000,7000,40,1,770,570,8,2021-Q2,NaN,NaN,NaN,NaN,NaN,NaN
1144,Virginia,8000,8500,530,6,3100,820,10,2021-Q2,NaN,NaN,NaN,NaN,NaN,NaN
1145,Washington,66000,122000,2900,2,9500,2600,2,2021-Q2,NaN,NaN,NaN,NaN,NaN,NaN
1146,West Virginia,8000,9000,170,2,1900,390,4,2021-Q2,NaN,NaN,NaN,NaN,NaN,NaN
1147,Wisconsin,42000,57000,2200,4,9000,7500,13,2021-Q2,NaN,NaN,NaN,NaN,NaN,NaN
1148,Wyoming,13500,30000,3400,11,7500,4900,16,2021-Q2,NaN,NaN,NaN,NaN,NaN,NaN
1149,Other,5970,8410,140,2,2890,3100,37,2021-Q2,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# Q2 of 2021 doesn't have any stressors data so I will do an inner join and keep that as my merged data
inner_merge = pd.merge(colony, stressors, on = (['State', 'Year']), how = 'inner')
inner_merge

,State,Starting Colonies,Maximum Colonies,Lost Colonies,Percent Loss,Added Colonies,Renovated Colonies,Percent Renovated,Year,Varroa Mites (Percent),Other pests and parasites (Percent),Diseases (percent),Pesticides (percent),Other (percent),Unknown (percent)
0,Alabama,7000,7000,1800,26,2800,250,4,2015-Q1,10.0,5.4,0.0,2.2,9.1,9.4
1,Arizona,35000,35000,4600,13,3400,2100,6,2015-Q1,26.9,20.5,0.1,0.0,1.8,3.1
2,Arkansas,13000,14000,1500,11,1200,90,1,2015-Q1,17.6,11.4,1.5,3.4,1.0,1.0
3,California,1440000,1690000,255000,15,250000,124000,7,2015-Q1,24.7,7.2,3.0,7.5,6.5,2.8
4,Colorado,3500,12500,1500,12,200,140,1,2015-Q1,14.6,0.9,1.8,0.6,2.6,5.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1099,Washington,48000,67000,6000,9,5500,850,1,2021-Q1,15.5,2.4,1.0,0.0,5.3,0.0
1100,West Virginia,7000,7500,1200,16,1700,720,10,2021-Q1,13.7,3.4,0.7,2.6,1.2,3.3
1101,Wisconsin,25000,37000,2500,7,7000,170,0,2021-Q1,16.1,0.0,0.0,0.0,3.6,3.2
1102,Wyoming,13000,14500,1700,12,500,1200,8,2021-Q1,0.0,0.0,0.0,0.0,3.3,7.9
1103,Other,6640,6640,540,8,600,70,1,2021-Q1,19.4,1.2,4.1,0.0,6.8,1.1

In [6]:
# remove 'Other' row
inner_merge = inner_merge[inner_merge.State != 'Other']
inner_merge

,State,Starting Colonies,Maximum Colonies,Lost Colonies,Percent Loss,Added Colonies,Renovated Colonies,Percent Renovated,Year,Varroa Mites (Percent),Other pests and parasites (Percent),Diseases (percent),Pesticides (percent),Other (percent),Unknown (percent)
0,Alabama,7000,7000,1800,26,2800,250,4,2015-Q1,10.0,5.4,0.0,2.2,9.1,9.4
1,Arizona,35000,35000,4600,13,3400,2100,6,2015-Q1,26.9,20.5,0.1,0.0,1.8,3.1
2,Arkansas,13000,14000,1500,11,1200,90,1,2015-Q1,17.6,11.4,1.5,3.4,1.0,1.0
3,California,1440000,1690000,255000,15,250000,124000,7,2015-Q1,24.7,7.2,3.0,7.5,6.5,2.8
4,Colorado,3500,12500,1500,12,200,140,1,2015-Q1,14.6,0.9,1.8,0.6,2.6,5.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1098,Virginia,7000,7000,1400,20,2300,50,1,2021-Q1,11.9,1.0,0.0,1.9,3.9,4.9
1099,Washington,48000,67000,6000,9,5500,850,1,2021-Q1,15.5,2.4,1.0,0.0,5.3,0.0
1100,West Virginia,7000,7500,1200,16,1700,720,10,2021-Q1,13.7,3.4,0.7,2.6,1.2,3.3
1101,Wisconsin,25000,37000,2500,7,7000,170,0,2021-Q1,16.1,0.0,0.0,0.0,3.6,3.2
1102,Wyoming,13000,14500,1700,12,500,1200,8,2021-Q1,0.0,0.0,0.0,0.0,3.3,7.9

In [8]:
inner_merge.reset_index(drop = True)

,State,Starting Colonies,Maximum Colonies,Lost Colonies,Percent Loss,Added Colonies,Renovated Colonies,Percent Renovated,Year,Varroa Mites (Percent),Other pests and parasites (Percent),Diseases (percent),Pesticides (percent),Other (percent),Unknown (percent)
0,Alabama,7000,7000,1800,26,2800,250,4,2015-Q1,10.0,5.4,0.0,2.2,9.1,9.4
1,Arizona,35000,35000,4600,13,3400,2100,6,2015-Q1,26.9,20.5,0.1,0.0,1.8,3.1
2,Arkansas,13000,14000,1500,11,1200,90,1,2015-Q1,17.6,11.4,1.5,3.4,1.0,1.0
3,California,1440000,1690000,255000,15,250000,124000,7,2015-Q1,24.7,7.2,3.0,7.5,6.5,2.8
4,Colorado,3500,12500,1500,12,200,140,1,2015-Q1,14.6,0.9,1.8,0.6,2.6,5.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1075,Virginia,7000,7000,1400,20,2300,50,1,2021-Q1,11.9,1.0,0.0,1.9,3.9,4.9
1076,Washington,48000,67000,6000,9,5500,850,1,2021-Q1,15.5,2.4,1.0,0.0,5.3,0.0
1077,West Virginia,7000,7500,1200,16,1700,720,10,2021-Q1,13.7,3.4,0.7,2.6,1.2,3.3
1078,Wisconsin,25000,37000,2500,7,7000,170,0,2021-Q1,16.1,0.0,0.0,0.0,3.6,3.2
1079,Wyoming,13000,14500,1700,12,500,1200,8,2021-Q1,0.0,0.0,0.0,0.0,3.3,7.9

In [19]:
#create a new dataframe that replaces 'State' with 'Region' then merge on all columns but state and region.

region = inner_merge['State'].replace(['Illinois', 'Indiana', 'Iowa', 'Ohio', 'Missouri', 'Michigan', 'Minnesota', 'Wisconsin', 'North Dakota', 'South Dakota', 'Nebraska', 'Kansas'], 'Midwest')

In [20]:
# export df to excel for use in Tableau

inner_merge.to_excel(r'C:\Users\geppe\OneDrive\Desktop\LaunchCode\Final-Project\data manipulation\colony_stressors_merged.xlsx', index = False)